version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: spring_crud_postgres_container
    environment:
      POSTGRES_DB: users_spring_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: